### ISSUE TITLE
set order of attributes

### ISSUE THREAD

**Issue by JHenneberg** [fortran-lang/stdlib#167]
While reading the style guide ```STYLE_GUIDE.md``` I noticed that the order of the attributes is not specified.

Going through the source files the order seems:
1. ```allocatable```
2. ```dimension```
3. ```intent(intent-spec)```
4. ```optional```

Although it is not clear if ```allocatable``` should be after oder before ```dimension```

Missing attributes I can think of right now are:
* ```target```, ```pointer```
* ```parameter```
* ```public```, ```private```, ```protected```
* ```asynchronous```
* ```save```
* ```external```
* ```contiguous```
* ```volatile```

So lets come up with a convention for the order of attributes.

Suggestion so far for ```STYLE_GUIDE.md```
```
# Order of attributes

Similiar to the guidlines for indentation and whitespace, specifiying the order of appearance of attributes can  help reviewing code and git-diffs.

1. ```allocatable```
2. ```dimension```
3. ```intent(<>)```
4. ...
```

**Comment by jvdp1** [comment]
Good point.
I usually write things in this order:

1. ```dimension```
2. ```allocatable```
3. ```intent(intent-spec)```
4. ```optional```

Some combinations of attributes are not possible.
Could you maybe submit a PR with suggested modifications for further discussions?

**Comment by certik** [comment]
I do not follow a strict order, although typically `intent()` is at the end, the `allocatable` and `dimension` I use in any order, and optional is typically around `intent()` in either order.

Is it important to always follow a certain order? It seems maybe we do not need to standardize this?

**Comment by milancurcic** [comment]
I tend to write these attributes in the same order as @jvdp1. More lately, I prefer to omit `dimension`, so:

```fortran
real, dimension(:), allocatable :: a
real, dimension(:,:), allocatable :: b
```

becomes just:

```fortran
real, allocatable :: a(:), b(:,:)
```

Not only is the code less verbose by not including `dimension`, but also arrays of different size, shape, or rank can be declared on the same line.

Like @certik, I don't think the order is as important. Rather than enforcing the order, I'd prefer seeing these two clauses:

* Don't use `dimension` attribute to declare arrays
* Always specify `intent` for dummy arguments

If we did indeed specify order of attributes in the style guide, I'd personally like to see:

* `intent` attribute should be specified last in the declaration statement
* If `optional` attribute is used to declare a dummy argument, it should follow the `intent` attribute

or similar.

**Comment by certik** [comment]
I agree with @milancurcic. I also prefer not to use `dimension`, the only exception is if I have a lot of arrays of the same dimension (of high rank), such as here:

https://github.com/certik/hfsolver/blob/b4c50c1979fb7e468b1852b144ba756f5a51788d/src/ofdft_fe.f90#L249

then it saves lots of typing.
