### ISSUE TITLE
stdlib_logger: proposition to add a logger for debug phases and levels among the different logs

### ISSUE THREAD

**Issue by jvdp1** [fortran-lang/stdlib#254]
I am playing with `stdlib_logger` and I think it would be nice to have a subroutine for messages that should be printed only during debug phases.

#### Syntax
`call self % log_debug( message [,module, procedure, stat, errmsg] )`

### Log levels
Log levels are used for filtering the messages based on their level/severity.
Each subroutine `log_error`, `log_information`, `log_io_error`, `log_text_error`, `log_warning`, and the additional `log_debug` is associated with a level.

For example:

* `log_debug` associated with `debug_level`
* `log_information` associated with `information_level`
* `log_warning` associated with `warning_level`
* `log_error`, `log_io_error`, `log_text_error` associated with `error_level`

with `debug_level` < `information_level` < `warning_level` < `error_level`.

Since `log_message` is called by all other `log` subroutines, it is probably best to not assign a level to `log_message` IMO.

The level of the logger should be set with the method `configure`, e.g. `call self %configure( level =  information_level)`, meaning that all calls with a level < `information_level` would be ignored.

Such log level options are avaible in [Julia](https://docs.julialang.org/en/v1/stdlib/Logging/#Log-event-structure) or [Python](https://docs.python.org/3/howto/logging.html) loggers.

@wclodius2 , @milancurcic , @14NGiestas , @ivan-pi , @certik is that of interests? any thoughs, comments?

**Comment by wclodius2** [comment]
A few comments. This is really two separate proposals" adding `log_debug` and adding `level`, and I think it would be best addressed by two separate PRs. Levels are also used by [FLIBS](http://flibs.sourceforge.net/) (`m_exception`). On the other hand, [Futility](https://github.com/CASL/Futility) (`exception_handler`) has separate flags for each "level", so that you can output "debug" while not outputting "information" or "warning". Testing the effects of `level` will be tricky. How do you verify what is not output? `log_text_error` is different from the other error levels. It indicates a problem not with the application, but rather with a file being read by the application. I suspect its output should be independent of `level`. Overall I am in favor of adding `log_debug`, but worry that adding `level` will be a bit tricky.

**Comment by jvdp1** [comment]
> A few comments. This is really two separate proposals" adding `log_debug` and adding `level`, and I think it would be best addressed by two separate PRs.

I agree with you that it should be two separate PR.

Re: `log_debug`, its implementation is straighfoward. The main question is about its API. Should it be similar to e.g., `log_information`,

```fortran
call self % log_debug( message [, module, procedure ] )
```
[Here](https://github.com/jvdp1/stdlib/blob/7941301fb28982ec15a10131f3320345ce1c2f8f/src/stdlib_logger.f90#L759) is a draft of `log_debug`.


>Levels are also used by [FLIBS](http://flibs.sourceforge.net/) (`m_exception`). On the other hand, [Futility](https://github.com/CASL/Futility) (`exception_handler`) has separate flags for each "level", so that you can output "debug" while not outputting "information" or "warning". 

The proposed approach in [this message](https://github.com/fortran-lang/stdlib/issues/254#issue-752902471) is similar to [Julia](https://docs.julialang.org/en/v1/stdlib/Logging/#Logging.LogLevel) and [Python](https://docs.python.org/3/howto/logging.html) loggers.
However, the approach proposed of [Futility](https://github.com/CASL/Futility) (`exception_handler`) seem to be more flexible, but more difficult to implement and manage (even for the user).

[Here](https://github.com/jvdp1/stdlib/blob/25c1226d866fef585142e37be8bad41cb35e3afb/src/stdlib_logger.f90#L71) is a draft for a proposition similar to Julia and Python loggers.
Note that the different default levels could be set by the user too.

>Testing the effects of `level` will be tricky. How do you verify what is not output? 

I don't understand that. For example, we could verify that a message is not printed to `output_unit`. [Here](https://github.com/jvdp1/stdlib/blob/25c1226d866fef585142e37be8bad41cb35e3afb/src/tests/logger/test_stdlib_logger.f90#L653) is a proposition for testing the different options.


>`log_text_error` is different from the other error levels. It indicates a problem not with the application, but rather with a file being read by the application. I suspect its output should be independent of `level`. 

Right. Default levels should be discussed first and set accordingly.

>Overall I am in favor of adding `log_debug`, but worry that adding `level` will be a bit tricky.

I am not sure what is tricky with the option `level` (at least in the way I imagine it). I might miss something about the 'level' approach.

**Comment by wclodius2** [comment]
The draft and the proposition for testing look mostly reasonable. A few comments on it:

1. There is one case of "...be NOT printed." that should be "...NOT be printed."
2. The levels have the prefix "stdlib_" that I consider wordy and superfluous. I consider the `stdlib_` prefix useful for avoiding naming conflicts between modules, but unnecessary for module entities. If you insist on a prefix I would make it "log_".
3. In the test code you use more vertical white space than I would now. I would not insert four blank lines to separate constructs. Because others objected to my inserting blank lines into my `if ... then ... else ... end if`, I no longer do that though you may be doing that to be consistent with my earlier style in the test code.
4. The `if ( self % level > stdlib_..._level) return` should have a blank between `level` and `)`.

**Comment by jvdp1** [comment]
Thank you for your comments. I integrated them, and submitted a first PR  (#256) for adding `log_debug`.

**Comment by wclodius2** [comment]
Great!

**Comment by 14NGiestas** [comment]
This issue was solved 9 Dec 2020 by #261 and probably can be closed.

**Comment by 14NGiestas** [comment]
I'm closing this issue since it was solved and merged in #261 .
