### ISSUE TITLE
Unable to build stdlib on low memory computer

### ISSUE THREAD

**Issue by brocolis** [fortran-lang/stdlib#281]
When I attempt to build stdlib with _make -f Makefile.manual_, gfortran eats all available memory and it makes the computer unusable. Unfortunately there was no way to know if the process was about to end, then after 30 minutes I manually killed the gfortran process.

Here are the screenshots.

_Command prompt_
![stdlib1](https://user-images.githubusercontent.com/5913872/103163902-e0862200-47e2-11eb-8ad2-3688719061e3.png)

_Task manager_
![stdlib2](https://user-images.githubusercontent.com/5913872/103163903-e1b74f00-47e2-11eb-8cf0-bb169b899634.png)

Computer: Windows 10 x64, Memory (total): 8GB
gfortran: 10.2.0, x64

**Comment by LKedward** [comment]
Hi @brocolis, please see [this comment](https://github.com/fortran-lang/stdlib/issues/217#issuecomment-689939274) for a solution previously mentioned.

This is an issue/solution that should be mentioned prominently in the README.

Since you're already using *fpm*, you may want to try the [stdlib-fpm](https://github.com/LKedward/stdlib-fpm) package which limits the maximum rank because of this issue.

---
Is there a way to exploit submodules here and break templated routines across different compilation units? This could better exploit parallelism during builds and reduce peak memory usage.

**Comment by brocolis** [comment]
Hi @LKedward . Both solutions work for me. Thank you.

**Comment by awvwgk** [comment]
> Is there a way to exploit submodules here and break templated routines across different compilation units? This could better exploit parallelism during builds and reduce peak memory usage.

I tried reducing the compilation load in #283 and got the default settings to compile with a maximal memory load of ~7 GB on two parallel build jobs.
