### ISSUE TITLE
Implement to_lower, to_upper, to_title and reverse for string_type

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/stdlib#335]
The `stdlib_string_type` currently only implements the bare minimum functionality. To start extending the functionality the functions `to_lower`, `to_upper`, `to_title` and `reverse` implemented in `stdlib_ascii` should be implemented for `stdlib_string_type` as well.

**Comment by Aman-Godara** [comment]
Hey! @awvwgk ,
Can I take this issue. I am working on strings project under GSoC 2021. So handling this will give me a good knowledge of the codebase as well.

**Comment by awvwgk** [comment]
@Aman-Godara Thanks, feel free to submit a patch for this issue. Let me know if you need any help,I recommend to start with forking the stdlib repo and compile a local version to make yourself familiar with the general workflow.

The implementation itself boils down to adding `interface` blocks and using `stdlib_ascii` in the `stdlib_string_type` module to add the new functionality. Also have a look at the tests in `src/tests` to add unit tests for the new functions and the specification in `doc/specs` to document the new functions.

**Comment by Aman-Godara** [comment]
@awvwgk Hey !,
Can you help please me with some of these problems?

1. Is there any way to access the ith character in character (let say of length = 9).
string = 'spiderman'
(I assume that fortran uses 1-based indexing.)
can I access the character at index 1 (which is 's') without using string(1:1)?

2. Is fortran a "call by reference" ("pass by reference") language? 
Many people say that python is "call by object deference", some argues that python is actually "call by value" because every variable stores reference and this reference is copied whenever called. (A one line answer would be enough)

3. Are characters (let's say of length = 10) mutable in Fortran? Which means that can I directly go and change the character at index 1 without affecting the rest of the indexes? 
In python strings are immutable just like tuples, so I will have to create a totally new character if I want to make any change.

4. How does fortran store character of length greater than 1. Does it use an array to store?

You don't have to invest too much into answering these questions, I will figure out most of the things on my own. Just wanted to know if I am thinking in the right direction or not.

**Comment by awvwgk** [comment]
@Aman-Godara I think the Fortran discourse is a better place to ask this questions.

**Comment by Aman-Godara** [comment]
Hey @awvwgk!,
I was going through the implementation of the `reverse` function in `stdlib_ascii`. The implementation has O(n) Space Complexity and since in fortran characters are mutable, can we implement the reverse function differently by taking advantage of this property? The only difference will be that the input itself will be modified.

**Comment by awvwgk** [comment]
Maybe as an addition, but not as a substitute for the current `reverse` function.

```f90
interface
    pure function reverse(string) result(reverse_string)
        character(len=*), intent(in) :: string
        character(len=len(string)) :: reverse_string
    end function reverse
end interface
```

This interface allow usage on character variables, which are in principle mutable, but in this context `intent(in)` and therefore immutable and character literals and parameters, which are immutable. A inplace reverse with an interface like the one below wouldn't work for the latter kind of character values and is therefore more limited in functionality.

```f90
interface
    pure subroutine reverse_inplace(string)
        character(len=*), intent(inout) :: string
    end subroutine reverse_inplace
end interface
```

You can of course propose an additional in place reverse subroutine for the stdlib.

**Comment by wclodius2** [comment]
Implementing `to_title` will require more than ASCII. Allowing more than just ASCII will require access to the Unicode character database, https://unicode.org/ucd/. This database will also be required for `to_upper`, `to_lower`, and `reverse` if more than ASCII is involved. This database consists of several tens of megabytes of files, http://www.unicode.org/Public/UCD/latest/, and including it in the Standard Library will be controversial, but requiring users to download and install it on their own will also be controversial. FWIW I have a couple of modules to process the more important files in the database.

**Comment by Aman-Godara** [comment]
What naming convention should I follow in `stdlib_string_type` module's interface. I cannot use `to_lower`, `to_upper`, `to_title` or `reverse` as the names for the interfaces that I am creating, as these corresponds to the names of the functions imported from `stdlib_ascii` module?
```Fortran
module stdlib_string_type
use stdlib_ascii, only: to_lower, to_upper, to_title, reverse

interface to_lower1
        module procedure :: to_lower_string
    end interface to_lower1
```
This is how the interface looks at this moment.

**Comment by awvwgk** [comment]
You can add an interface block to `stdlib_ascii` as well, this allows you to use the same name in both modules:
```f90
interface to_lower
    module procedure :: to_lower
end interface to_lower
```
