### ISSUE TITLE
Median

### ISSUE THREAD

**Issue by Beliavsky** [fortran-lang/stdlib#377]
I suggest that the descriptive statistics section include the median. Alan Miller's [median.f90 ](https://jblevins.org/mirror/amiller/median.f90) could be used. Arguably any library that has a function for the mean should also have one for the median, since the latter is a more robust measure of central tendency (although less efficient than the arithmetic mean for Gaussian data).

**Comment by jvdp1** [comment]
Thank you for opening this thread. I agree with you that `stdlib` should include a function for the median (but also for the quartiles,..). However, such functions need sorting algorithms. This might be solved in a near-future with #98. I think it is better to rely on a module that provide general algorithms, instead of implementing its own algorithm as in Alan Miller 's code.

This issue is also related to #113 in which such a function was already proposed.

**Comment by 14NGiestas** [comment]
Closing this issue since it was addressed by #426, stdlib has `median` since [v0.1.0](https://github.com/fortran-lang/stdlib/releases/tag/v0.1.0)
