### ISSUE TITLE
fypp for tests?

### ISSUE THREAD

**Issue by ghbrown** [fortran-lang/stdlib#496]
I considered bringing this up in the Discourse, but figured here was a more relevant place.

**My question boils down to this**: is there a reason we are not taking advantage of `fypp` for the `stdlib` tests (all of the test files I have seen are `.f90`)? Especially for mathematical functions where one needs to test reals, complex, and integers, a few lines of `fypp` could compress the source code (pre-fypp) by more than 3 to 1 by looping over the kinds of reals, complex, and integers.

I am sure there may be a good reason, but I have performed a quick search in the Discourse and in other GitHub issues (turning up nothing) and tried to reason about it (also turning up nothing).

**Comment by awvwgk** [comment]
The reason are probably the build system limitations, the CMake tests are currently generated by an ugly macro and the manual Makefile tests by an include file template, both approaches lack the required flexibility to mix fypp preprocessed files and normal Fortran source code. It doesn't mean it is impossible, but the result is suboptimal at best.

Rather than over-engineering our build systems further, I think the first step is adopting some testing framework and bundle together all tests in a consistent way, we acquired quite some different styles now in the testsuites. For this purpose we discussed using [vegetables], [fytest] or [test-drive] in https://github.com/fortran-lang/stdlib/issues/162 and are now in the process of adopting [test-drive] in #494.

[vegetables]: https://gitlab.com/everythingfunctional/vegetables
[fytest]: https://github.com/aradi/fytest
[test-drive]: https://github.com/awvwgk/test-drive

Using fypp in the testsuite will be mainly useful for conditionally skipping tests in case the compiler does not support some of our requirements.

**Comment by ghbrown** [comment]
I see, thanks for the detailed explanation. Great to hear that some plans for improvement are in motion though!

I'm going to close the issue so as not to pollute the Issues.

**Comment by jvdp1** [comment]
fypp is already used for the tests, e.g., see [`test_median.fypp`](
https://github.com/fortran-lang/stdlib/blob/47d0a00420e5257e7a95271fc04b7240f1ce4a89/src/tests/stats/test_median.fypp).
But indeed, its use should be extended to other tests. As Sebastian said,
it is currently being discussed/tested/implemented.

Le mar. 24 août 2021 à 23:54, Gabriel Brown ***@***.***> a
écrit :
