### ISSUE TITLE
Should we continue maintaining the manual Makefiles?

### ISSUE THREAD

**Issue by milancurcic** [fortran-lang/stdlib#526]
With stdlib now being also an fpm package, as well as CMake support, should we continue maintaining the manual Makefiles?

I argued for manual Makefiles early on (before fpm) due to the possible absence of CMake or a sufficient version of CMake on many systems. However, the cost of maintaining manual Makefiles is quite high relative to the fpm or CMake build. For example, adding a new module and tests requires editing multiple Makefiles in the source tree. And it gets messier when trying to merge some older PRs, as the manual Makefiles would often be in conflict with the target branch.

We could run a poll on Discourse and see what users there think. I think this may be a good time to remove manual Makefile support. What do you think?

**Comment by jvdp1** [comment]
I also agree on dropping the Makefile.

**Comment by milancurcic** [comment]
Discourse poll [here](https://fortran-lang.discourse.group/t/how-do-you-build-the-fortran-stdlib/1862).

**Comment by certik** [comment]
Now when `fpm` supports `stdlib`, I am fine dropping them.

I don't have time *right* now, but I really want to provide `cmake` and `make` backends for `fpm`. That way we only have to make sure things build using `fpm` in `stdlib`, and `fpm` takes care of `cmake` and `make` and we can also add `meson`, etc.

**Comment by 14NGiestas** [comment]
Keeping a makefile for a project like this is kinda annoying because of the non-trivial dependencies and it tends to get outdated. I usually don't like `cmake` much because I always forget the -DMAXRANK... thing... err... well I forgot again but it works well enough and isn't so complicated adding new files to it. 
Also with `fpm` I just run the `./ci/fpm_deployment.sh`, `cd stdlib-fpm`, and I can review a patch easily, build it, create a quick `app/main.f90` to play around.
