### ISSUE TITLE
Collect distribution modules in stdlib_stats_distribution

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/stdlib#544]
@Jim-215-Fisher in https://github.com/fortran-lang/stdlib/pull/538#issuecomment-932976436

> Regarding to stdlib_stats_distribution_PRNG module, I am not sure whether it should be in stats_distribution package. GSL has a separate random numbers package in addition to random distributions and statistics.

Should `stdlib_stats_distribution_PRNG` become a submodule of `stdlib_stats_distribution`?

**Comment by milancurcic** [comment]
I think it should be in the `stdlib_random` module.

**Comment by jvdp1** [comment]
I though a bit about yesterday while reviewing #272. However, there are other PRs proposing similar functions. Therefore I decided to review first these other PRs, before taking a decision ;) I am a bit puzzled because these modules provide procedures related to the distributions (pdf, cdf) and to randomness (rnd). I wonder if it would not be better to generate 2 different modules (distribution vs random)

**Comment by Jim-215-Fisher** [comment]
I think PRNG should be in a separate `random` module as GSL does. PRNG generates random integer numbers with defined kind which could be used for applications way beyond of random distributions. Furthermore, PRNG may contain parallel version of generators in the future.
